/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import br.com.projeto.dao.Clientedao;
import br.com.projeto.dao.Funcionariodao;
import br.com.projeto.modelo.Cliente;
import br.com.projeto.modelo.Funcionarios;
import br.com.projeto.modelo.Utilitarios;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WEB-01
 */
public class FRM_Cadastro_Funcionario extends javax.swing.JFrame {

    public void listar() {

        Funcionariodao dao = new Funcionariodao();
        List<Funcionarios> lista = dao.listarfuncionario();
        DefaultTableModel dados = (DefaultTableModel) ftabelafuncionario.getModel();
        dados.setNumRows(0);

        for (Funcionarios c : lista) {

            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getRg(),
                c.getCpf(),
                c.getEmail(),
                c.getSenha(),
                c.getCargo(),
                c.getNivel_acesso(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereço(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getEstado(),});

        }

    }
    public FRM_Cadastro_Funcionario() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        paineldadospessoais = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtfcodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfemail = new javax.swing.JTextField();
        txtfcpf = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtftelefone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtfcelular = new javax.swing.JFormattedTextField();
        txtfnome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfrg = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txtfcep = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        txtfendereço = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtfcidade = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtfbairro = new javax.swing.JTextField();
        txtfcomplemento = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtfnumero = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        boxtxtfestado = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        btfexcluir_dados = new javax.swing.JToggleButton();
        btfeditar_dados = new javax.swing.JToggleButton();
        btfsalvar_dados = new javax.swing.JToggleButton();
        btfnovo_dados = new javax.swing.JToggleButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtfcargo = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        boxtxtfnivel = new javax.swing.JComboBox<>();
        txtfsenha = new javax.swing.JPasswordField();
        painelconsultacliente = new javax.swing.JPanel();
        txtfpesquisa = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ftabelafuncionario = new javax.swing.JTable();
        btfpesquisa = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mega Click");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Funcionarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        paineldadospessoais.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome do Cliente: ");

        txtfcodigo.setEditable(false);
        txtfcodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtfcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfcodigoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CPF:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Email:");

        txtfemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfemailActionPerformed(evt);
            }
        });

        try {
            txtfcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Telefone Fixo:");

        try {
            txtftelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Celular:");

        try {
            txtfcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtfnome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtfnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnomeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Código:");

        try {
            txtfrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("RG:");

        try {
            txtfcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfcep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfcepKeyPressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Cep:");

        txtfendereço.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtfendereço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfendereçoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Endereço:");

        txtfcidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtfcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfcidadeActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Cidade:");

        txtfbairro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtfbairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfbairroActionPerformed(evt);
            }
        });

        txtfcomplemento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtfcomplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfcomplementoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Complemento:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Bairro:");

        txtfnumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtfnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnumeroActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("N°:");

        boxtxtfestado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxtxtfestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("UF:");

        btfexcluir_dados.setText("Excluir");
        btfexcluir_dados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfexcluir_dadosActionPerformed(evt);
            }
        });

        btfeditar_dados.setText("Editar");
        btfeditar_dados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfeditar_dadosActionPerformed(evt);
            }
        });

        btfsalvar_dados.setText("Salvar");
        btfsalvar_dados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfsalvar_dadosActionPerformed(evt);
            }
        });

        btfnovo_dados.setText("+ Novo");
        btfnovo_dados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfnovo_dadosActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Senha:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Cargo:");

        txtfcargo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtfcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfcargoActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Nivel de Acesso:");

        boxtxtfnivel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boxtxtfnivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuário" }));
        boxtxtfnivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxtxtfnivelActionPerformed(evt);
            }
        });

        txtfsenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout paineldadospessoaisLayout = new javax.swing.GroupLayout(paineldadospessoais);
        paineldadospessoais.setLayout(paineldadospessoaisLayout);
        paineldadospessoaisLayout.setHorizontalGroup(
            paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                        .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel18)
                                .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtftelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfemail, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel22))
                                    .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                                        .addComponent(txtfendereço, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel20)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxtxtfestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                        .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel2))
                                    .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                                        .addComponent(txtfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfnome, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56)
                                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtfcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(93, 93, 93)
                                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(txtfrg, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                                .addGap(369, 369, 369)
                                .addComponent(btfnovo_dados, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btfsalvar_dados, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btfeditar_dados, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btfexcluir_dados, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfcep, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boxtxtfnivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paineldadospessoaisLayout.setVerticalGroup(
            paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paineldadospessoaisLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtftelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtfcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtfcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtfendereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtfnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(txtfcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtfbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22)
                    .addComponent(boxtxtfestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(25, 25, 25)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(boxtxtfnivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(txtfsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(179, 179, 179)
                .addGroup(paineldadospessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btfsalvar_dados)
                    .addComponent(btfeditar_dados)
                    .addComponent(btfexcluir_dados)
                    .addComponent(btfnovo_dados))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Pessoais", paineldadospessoais);

        painelconsultacliente.setBackground(new java.awt.Color(204, 204, 204));

        txtfpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfpesquisaActionPerformed(evt);
            }
        });
        txtfpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfpesquisaKeyReleased(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome" }));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        ftabelafuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "rg", "cpf", "email", "Senha", "Cargo", "Nível de acesso", "telefone", "celular", "cep", "endereco", "numero", "complemento", "bairro", "cidade", "estado"
            }
        ));
        ftabelafuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftabelafuncionarioMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ftabelafuncionario);

        btfpesquisa.setText("Pesquisar");
        btfpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfpesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelconsultaclienteLayout = new javax.swing.GroupLayout(painelconsultacliente);
        painelconsultacliente.setLayout(painelconsultaclienteLayout);
        painelconsultaclienteLayout.setHorizontalGroup(
            painelconsultaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelconsultaclienteLayout.createSequentialGroup()
                .addGroup(painelconsultaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelconsultaclienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(painelconsultaclienteLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btfpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 526, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelconsultaclienteLayout.setVerticalGroup(
            painelconsultaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelconsultaclienteLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(painelconsultaclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btfpesquisa)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jTabbedPane1.addTab("Consulta de Funcionarios", painelconsultacliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1251, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtfcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfcodigoActionPerformed

    private void txtfemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfemailActionPerformed

    private void txtfnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnomeActionPerformed

    private void txtfcepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfcepKeyPressed

        
	if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
         Cliente obj =  new Cliente();
         Clientedao dao = new Clientedao();
         obj = dao.buscaCep(txtfcep.getText());
         
         txtfendereço.setText(obj.getEndereço());
         txtfbairro.setText(obj.getBairro());
         txtfcidade.setText(obj.getCidade());
         boxtxtfestado.setSelectedItem(obj.getEstado());               
         System.out.println(obj.getEstado());
         
     } 
                                     
    }//GEN-LAST:event_txtfcepKeyPressed

    private void txtfendereçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfendereçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfendereçoActionPerformed

    private void txtfcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfcidadeActionPerformed

    private void txtfbairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfbairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfbairroActionPerformed

    private void txtfcomplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfcomplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfcomplementoActionPerformed

    private void txtfnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnumeroActionPerformed

    private void btfexcluir_dadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfexcluir_dadosActionPerformed
  
        try {

            Funcionarios obj = new Funcionarios();

            
            obj.setId(Integer.parseInt(txtfcodigo.getText()));

            Funcionariodao dao = new Funcionariodao();

            dao.excluirFuncionario(obj);
            new Utilitarios().limpatela(paineldadospessoais);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"erro :" + e);
        }
                                    
    }//GEN-LAST:event_btfexcluir_dadosActionPerformed

    private void btfeditar_dadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfeditar_dadosActionPerformed
    
         try {
            
        
            Funcionarios obj = new Funcionarios();

            obj.setNome(txtfnome.getText());
            obj.setRg(txtfrg.getText());
            obj.setCpf(txtfcpf.getText());
            obj.setEmail(txtfemail.getText());
            obj.setSenha(txtfsenha.getText());
            obj.setCargo(txtfcargo.getText());
            obj.setNivel_acesso(boxtxtfnivel.getSelectedItem().toString());
            obj.setTelefone(txtftelefone.getText());
            obj.setCelular(txtfcelular.getText());
            obj.setCep(txtfcep.getText());
            obj.setEndereço(txtfendereço.getText());
            obj.setNumero(Integer.parseInt(txtfnumero.getText()));
            obj.setComplemento(txtfcomplemento.getText());
            obj.setBairro(txtfbairro.getText());
            obj.setCidade(txtfcidade.getText());
            obj.setEstado(boxtxtfestado.getSelectedItem().toString());
            obj.setId(Integer.parseInt(txtfcodigo.getText()));

            Funcionariodao dao = new Funcionariodao();

            dao.alterarFuncionario(obj);
            
            new Utilitarios().limpatela(paineldadospessoais);
} catch (Exception e) {
    JOptionPane.showMessageDialog(null,"erro :" + e);
        }
    }//GEN-LAST:event_btfeditar_dadosActionPerformed

    private void btfsalvar_dadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfsalvar_dadosActionPerformed

        try {

            Funcionarios obj = new Funcionarios();

            obj.setNome(txtfnome.getText());
            obj.setRg(txtfrg.getText());
            obj.setCpf(txtfcpf.getText());
            obj.setEmail(txtfemail.getText());
            obj.setSenha(txtfsenha.getText());
            obj.setCargo(txtfcargo.getText());
            obj.setNivel_acesso(boxtxtfnivel.getSelectedItem().toString());
            obj.setTelefone(txtftelefone.getText());
            obj.setCelular(txtfcelular.getText());
            obj.setCep(txtfcep.getText());
            obj.setEndereço(txtfendereço.getText());
            obj.setNumero(Integer.parseInt(txtfnumero.getText()));
            obj.setComplemento(txtfcomplemento.getText());
            obj.setBairro(txtfbairro.getText());
            obj.setCidade(txtfcidade.getText());
            obj.setEstado(boxtxtfestado.getSelectedItem().toString());

            Funcionariodao dao = new Funcionariodao();

            dao.cadastrarfuncionario(obj);
            new Utilitarios().limpatela(paineldadospessoais);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null,"erro :" + e);
        }

    }//GEN-LAST:event_btfsalvar_dadosActionPerformed

    private void btfnovo_dadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfnovo_dadosActionPerformed
    new Utilitarios().limpatela(paineldadospessoais);
    }//GEN-LAST:event_btfnovo_dadosActionPerformed

    private void txtfcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfcargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfcargoActionPerformed

    private void boxtxtfnivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxtxtfnivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxtxtfnivelActionPerformed

    private void txtfpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfpesquisaActionPerformed

    }//GEN-LAST:event_txtfpesquisaActionPerformed

    private void txtfpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfpesquisaKeyReleased

    }//GEN-LAST:event_txtfpesquisaKeyReleased

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void ftabelafuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftabelafuncionarioMouseClicked
    
        jTabbedPane1.setSelectedIndex(0);
        txtfcodigo.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 0).toString());
        txtfnome.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 1).toString());
        txtfrg.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 2).toString());
        txtfcpf.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 3).toString());
        txtfemail.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 4).toString());
        txtfsenha.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 5).toString());
        txtfcargo.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 6).toString());
        boxtxtfnivel.setSelectedItem(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 7).toString());
        txtftelefone.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 8).toString());
        txtfcelular.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 9).toString());
        txtfcep.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 10).toString());
        txtfendereço.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 11).toString());
        txtfnumero.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 12).toString());
        txtfcomplemento.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 13).toString());
        txtfbairro.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 14).toString());
        txtfcidade.setText(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 15).toString());
        boxtxtfestado.setSelectedItem(ftabelafuncionario.getValueAt(ftabelafuncionario.getSelectedRow(), 16).toString());
    }//GEN-LAST:event_ftabelafuncionarioMouseClicked

    private void btfpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfpesquisaActionPerformed
 String nome = "%"+txtfpesquisa.getText()+"%";
       
        Funcionariodao dao = new Funcionariodao();
        List<Funcionarios> lista = dao.Buscafuncionario(nome);
        DefaultTableModel dados = (DefaultTableModel) ftabelafuncionario.getModel();
        dados.setNumRows(0);
        
        for (Funcionarios c : lista) {

            dados.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getRg(),
                c.getCpf(),
                c.getEmail(),
                c.getSenha(),
                c.getCargo(),
                c.getNivel_acesso(),
                c.getTelefone(),
                c.getCelular(),
                c.getCep(),
                c.getEndereço(),
                c.getNumero(),
                c.getComplemento(),
                c.getBairro(),
                c.getCidade(),
                c.getEstado(),});

        }
    }//GEN-LAST:event_btfpesquisaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Cadastro_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Cadastro_Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxtxtfestado;
    private javax.swing.JComboBox<String> boxtxtfnivel;
    private javax.swing.JToggleButton btfeditar_dados;
    private javax.swing.JToggleButton btfexcluir_dados;
    private javax.swing.JToggleButton btfnovo_dados;
    private javax.swing.JToggleButton btfpesquisa;
    private javax.swing.JToggleButton btfsalvar_dados;
    private javax.swing.JTable ftabelafuncionario;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel painelconsultacliente;
    private javax.swing.JPanel paineldadospessoais;
    private javax.swing.JTextField txtfbairro;
    private javax.swing.JTextField txtfcargo;
    private javax.swing.JFormattedTextField txtfcelular;
    private javax.swing.JFormattedTextField txtfcep;
    private javax.swing.JTextField txtfcidade;
    private javax.swing.JTextField txtfcodigo;
    private javax.swing.JTextField txtfcomplemento;
    private javax.swing.JFormattedTextField txtfcpf;
    private javax.swing.JTextField txtfemail;
    private javax.swing.JTextField txtfendereço;
    private javax.swing.JTextField txtfnome;
    private javax.swing.JTextField txtfnumero;
    private javax.swing.JTextField txtfpesquisa;
    private javax.swing.JFormattedTextField txtfrg;
    private javax.swing.JPasswordField txtfsenha;
    private javax.swing.JFormattedTextField txtftelefone;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Ícone.png")));
    }
}
