/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author WEB-01
 */
public class FRMTeleprincipal extends javax.swing.JFrame {

    
    public String Usuario_logado;

    /**
     *
     */
    public Date data;
    public FRMTeleprincipal() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btvendas_controle = new javax.swing.JMenu();
        btcontroledepedidos = new javax.swing.JMenuItem();
        btcontroledia = new javax.swing.JMenuItem();
        bt_historico = new javax.swing.JMenuItem();
        tb_produtos = new javax.swing.JMenu();
        bt_produtos_consulta = new javax.swing.JMenuItem();
        bt_produtos_consulta1 = new javax.swing.JMenuItem();
        tb_produtos_estoque = new javax.swing.JMenuItem();
        bt_clientes = new javax.swing.JMenu();
        bt_clientes_controle = new javax.swing.JMenuItem();
        bt_cadastro_cliente = new javax.swing.JMenuItem();
        bt_fornecedores = new javax.swing.JMenu();
        bt_fornecedores_controle = new javax.swing.JMenuItem();
        bt_funcionarios = new javax.swing.JMenu();
        bt_funcionarios_controle = new javax.swing.JMenuItem();
        bt_config = new javax.swing.JMenu();
        bt_config_trocausuario = new javax.swing.JMenuItem();
        bt_sairdosistema = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mega Click");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/Fundo1.jpg"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Usuário:");

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btvendas_controle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/vendas.png"))); // NOI18N
        btvendas_controle.setText("Vendas");

        btcontroledepedidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        btcontroledepedidos.setText("Controle de Pedidos de Vendas");
        btcontroledepedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcontroledepedidosActionPerformed(evt);
            }
        });
        btvendas_controle.add(btcontroledepedidos);

        btcontroledia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        btcontroledia.setText("Controle do Dia");
        btcontroledia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcontrolediaActionPerformed(evt);
            }
        });
        btvendas_controle.add(btcontroledia);

        bt_historico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        bt_historico.setText("Histórico de Vendas");
        bt_historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_historicoActionPerformed(evt);
            }
        });
        btvendas_controle.add(bt_historico);

        jMenuBar1.add(btvendas_controle);

        tb_produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/produtos.png"))); // NOI18N
        tb_produtos.setText("Produtos");

        bt_produtos_consulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        bt_produtos_consulta.setText("Consulta de Produtos");
        bt_produtos_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_produtos_consultaActionPerformed(evt);
            }
        });
        tb_produtos.add(bt_produtos_consulta);

        bt_produtos_consulta1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        bt_produtos_consulta1.setText("Cadastrar Produto");
        bt_produtos_consulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_produtos_consulta1ActionPerformed(evt);
            }
        });
        tb_produtos.add(bt_produtos_consulta1);

        tb_produtos_estoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        tb_produtos_estoque.setText("Controle de Estoque");
        tb_produtos_estoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_produtos_estoqueMouseClicked(evt);
            }
        });
        tb_produtos_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_produtos_estoqueActionPerformed(evt);
            }
        });
        tb_produtos.add(tb_produtos_estoque);

        jMenuBar1.add(tb_produtos);

        bt_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/clientes.png"))); // NOI18N
        bt_clientes.setText("Clientes");

        bt_clientes_controle.setText("Controle de Clientes");
        bt_clientes_controle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clientes_controleActionPerformed(evt);
            }
        });
        bt_clientes.add(bt_clientes_controle);

        bt_cadastro_cliente.setText("Cadastro de Clientes");
        bt_cadastro_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastro_clienteActionPerformed(evt);
            }
        });
        bt_clientes.add(bt_cadastro_cliente);

        jMenuBar1.add(bt_clientes);

        bt_fornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/fornecedores.png"))); // NOI18N
        bt_fornecedores.setText("Fornecedores");

        bt_fornecedores_controle.setText("Controle de Fornecedores");
        bt_fornecedores_controle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fornecedores_controleActionPerformed(evt);
            }
        });
        bt_fornecedores.add(bt_fornecedores_controle);

        jMenuBar1.add(bt_fornecedores);

        bt_funcionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/funcionarios.png"))); // NOI18N
        bt_funcionarios.setText("Funcionários");

        bt_funcionarios_controle.setText("Contorle de Funcionários");
        bt_funcionarios_controle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_funcionarios_controleActionPerformed(evt);
            }
        });
        bt_funcionarios.add(bt_funcionarios_controle);

        jMenuBar1.add(bt_funcionarios);

        bt_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/configuracoes.png"))); // NOI18N
        bt_config.setText("Configurações");

        bt_config_trocausuario.setText("Troca de Usuários");
        bt_config_trocausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_config_trocausuarioActionPerformed(evt);
            }
        });
        bt_config.add(bt_config_trocausuario);

        jMenuBar1.add(bt_config);

        bt_sairdosistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projeto/imagens/sair.png"))); // NOI18N
        bt_sairdosistema.setText("Sair do Sistema");
        bt_sairdosistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_sairdosistemaMouseClicked(evt);
            }
        });
        jMenuBar1.add(bt_sairdosistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_clientes_controleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clientes_controleActionPerformed
     FRM_Cadastro_Cliente cc = new FRM_Cadastro_Cliente();
     cc.jTabbedPane1.setSelectedIndex(1);
     cc.setVisible(true);
    }//GEN-LAST:event_bt_clientes_controleActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setExtendedState(this.MAXIMIZED_BOTH);
        txtUsuario.setText(Usuario_logado);
        this.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void tb_produtos_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_produtos_estoqueActionPerformed
       FRM_Controle_Estoque T = new FRM_Controle_Estoque();
       T.setVisible(true);
       
    }//GEN-LAST:event_tb_produtos_estoqueActionPerformed

    private void bt_config_trocausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_config_trocausuarioActionPerformed
        FRM_Login fl = new FRM_Login();
        this.dispose();
        
        fl.setVisible(true);
    }//GEN-LAST:event_bt_config_trocausuarioActionPerformed

    private void bt_sairdosistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_sairdosistemaMouseClicked
        int op;
        
        op = JOptionPane.showConfirmDialog(null,"Tem certeza que dejesa sair ?");
        
        if(op ==0){
            System.exit(0);
        }
    }//GEN-LAST:event_bt_sairdosistemaMouseClicked

    private void bt_produtos_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_produtos_consultaActionPerformed
       FRM_Cadastro_Produtos cp = new FRM_Cadastro_Produtos();
       cp.jTabbedPane1.setSelectedIndex(1);
       cp.setVisible(true);
    }//GEN-LAST:event_bt_produtos_consultaActionPerformed

    private void bt_cadastro_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastro_clienteActionPerformed
       FRM_Cadastro_Cliente c = new FRM_Cadastro_Cliente();
       c.setVisible(true);
    }//GEN-LAST:event_bt_cadastro_clienteActionPerformed

    private void btcontroledepedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcontroledepedidosActionPerformed
    FRM_Pontovendas P = new FRM_Pontovendas();
    P.setVisible(true);
    }//GEN-LAST:event_btcontroledepedidosActionPerformed

    private void bt_historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_historicoActionPerformed
        FRM_Historico h = new FRM_Historico();
        h.setVisible(true);
    }//GEN-LAST:event_bt_historicoActionPerformed

    private void bt_fornecedores_controleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fornecedores_controleActionPerformed
        FRM_Cadastro_Fornecedores C = new FRM_Cadastro_Fornecedores();
        C.setVisible(true);
    }//GEN-LAST:event_bt_fornecedores_controleActionPerformed

    private void bt_funcionarios_controleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_funcionarios_controleActionPerformed
        FRM_Cadastro_Funcionario F = new FRM_Cadastro_Funcionario();
        F.setVisible(true);
    }//GEN-LAST:event_bt_funcionarios_controleActionPerformed

    private void btcontrolediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcontrolediaActionPerformed
        FRM_Total_Venda V = new FRM_Total_Venda();
        V.setVisible(true);
    }//GEN-LAST:event_btcontrolediaActionPerformed

    private void bt_produtos_consulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_produtos_consulta1ActionPerformed
     FRM_Cadastro_Produtos P = new FRM_Cadastro_Produtos();
     P.setVisible(true);
    }//GEN-LAST:event_bt_produtos_consulta1ActionPerformed

    private void tb_produtos_estoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_produtos_estoqueMouseClicked
      
    }//GEN-LAST:event_tb_produtos_estoqueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMTeleprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMTeleprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMTeleprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMTeleprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMTeleprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem bt_cadastro_cliente;
    private javax.swing.JMenu bt_clientes;
    public javax.swing.JMenuItem bt_clientes_controle;
    private javax.swing.JMenu bt_config;
    public javax.swing.JMenuItem bt_config_trocausuario;
    private javax.swing.JMenu bt_fornecedores;
    public javax.swing.JMenuItem bt_fornecedores_controle;
    private javax.swing.JMenu bt_funcionarios;
    public javax.swing.JMenuItem bt_funcionarios_controle;
    public javax.swing.JMenuItem bt_historico;
    public javax.swing.JMenuItem bt_produtos_consulta;
    public javax.swing.JMenuItem bt_produtos_consulta1;
    private javax.swing.JMenu bt_sairdosistema;
    public javax.swing.JMenuItem btcontroledepedidos;
    public javax.swing.JMenuItem btcontroledia;
    private javax.swing.JMenu btvendas_controle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenu tb_produtos;
    public javax.swing.JMenuItem tb_produtos_estoque;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
private void setIcon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Ícone.png")));
    }
}
